---
- name: Set main crontab variables
  cronvar:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    cron_file: '{{ cron__main_file }}'
  with_dict: '{{ cron__envs }}'

- name: Configure main crontab jobs
  cron:
    name: '{{ item.key }}'
    day: '{{ item.value.day|d(omit) }}'
    month: '{{ item.value.month|d(omit) }}'
    weekday: '{{ item.value.weekday|d(omit) }}'
    hour: '{{ item.value.hour|d(omit) }}'
    minute: '{{ item.value.minute|d(omit) }}'
    special_time: '{{ item.value.special_time|d(omit) }}'
    job: '{{ item.value.job }}'
    user: '{{ item.value.user|d(omit) }}'
    cron_file: '{{ cron__main_file }}'
    disabled: '{{ item.value.disabled|d(False)|bool }}'
    state: "{{ item.value.state|d('present') }}"
  with_dict: '{{ cron__jobs }}'
