---
# tasks file for cron

- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      skip: true
  tags: ['always']

- import_tasks: install.yml
  tags: ['cron', 'cron-install']

- import_tasks: configure.yml
  tags: ['cron', 'cron-configure']

- import_tasks: service.yml
  tags: ['cron', 'cron-service']
